### ISSUE TITLE
Switching Ctnrs in Ctnr detail view doesn't redirect to switched Ctnr.

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/chili#14]
Steps to Reproduce:
When in Ctnr foo's detail page, switch to Ctnr bar with the dropdown.

Expected:
Redirected to Ctnr bar's detail page.

Actual:
Staying on Ctnr foo's detail page.

**Comment by ngokevin** [comment]
core/ctnr/views:change_ctnr

**Comment by church29** [comment]
Fixed!
if 'ctnr' in referer.split('/'):
    referer = reverse('ctnr-detail', kwargs={'pk': ctnr.id})

**Comment by murrown** [comment]
this isn't working for me anymore

to reproduce the behavior:
select zone.wave from dropdown
click on zone.wave link to access detail view
select zone.ads-fn from dropdown
the detail view remains in zone.wave even though the selected container is zone.ads-fn

**Comment by church29** [comment]
I don't have my database filled at all so I can't reproduce that. I changed it a slight bit to remove the header of the address and compare the rest to the address of the previous id. Should work just fine if there aren't any drastic changes in the urls.
