### ISSUE TITLE
Sort Ctnr dropdown alphabetically

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/chili#16]
In cyuser/views:login_session

global and default are reserved so have them at the top.

Remove the duplicate Ctnr name of the current Ctnr from the dropdown.
(ex: global, global, default)

**Comment by church29** [comment]
from django.db.models import Q

request.session['ctnrs'] = (list(Ctnr.objects.filter(Q(name="default") | Q(name="global"))) + list(Ct    nr.objects.exclude(Q(name="default") | Q(name="global")).order_by("name").all()))i

Starts the list with default and global, then excludes it from the main call which is ordered by name.

**Comment by ngokevin** [comment]
The current Ctnr will not always be "default" or "local". It could be any arbitrary Ctnr. If I am on Ctnr "foo", I should still be able to see "global" and "default", but not "foo" twice in the dropdown.

(ex: foo, global default, foo)

You also don't have to call .all() if you are already filtering or doing an order_by.

It'd also be better to use the Ctnr's primary key/id when referring to global and default. They have id's of 0 and 1 respectively.

Good start though.

**Comment by church29** [comment]
42             <select name="ctnr_name" class="submit-on-change">
 43               {% for ctnr in request.session.ctnrs %}
 44                 {% if ctnr==request.session.ctnr %}
 45                     <option selected="selected" value="{{ ctnr }}">{{ ctnr.name }}</option>
 46                 {% else %}
 47                     <option value="{{ ctnr }}">{{ ctnr.name }}</option>
 48                 {% endif %}
 49               {% endfor %}
 50             </select>

**Comment by murrown** [comment]
this issue is "solved", but required me to log out before it would take effect
this might be a problem because if the list of containers changes while a user is logged in, the dropdown might not change until after they log out

**Comment by ngokevin** [comment]
yeah, but it's not too big a deal. would require too much work to fix
