### ISSUE TITLE
User (detail) profile page

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/chili#17]
When clicking the username on the top bar, nothing happens.
Give that link a (reversed) url leading to a user detail profile page.

The page should contain two tables for now:
1. User detail table (username, email); this should only be one row of data
2. CtnrUser table (ctnrs the user belongs to, permission level like admin or user)

Notable pieces of code to read:
1. UserProfile model (cyuser/models.py) and User urls (cyuser/urls.py)
2. CtnrUser model (ctnr/models.py)
3. tablefy function (base/utils.py)
4. cydns view as an example of how tables are hooked up (cydns/views.py and cydns/templates/cydns/cydns_view.html)

Ask me if you have any questions. Thanks!

**Comment by church29** [comment]
Added the basic view of username and email
Still need the CtnrUser table

**Comment by church29** [comment]
Added CtnrUser table. Still needs some final formatting. UserDetailView is a basic function rather then a class. This might be changed very soon.

**Comment by ngokevin** [comment]
Yeah, you're free to try to make some generic view (class based or function based, whichever looks nicer) for all of the detail views. Like the detail views for DHCP mostly follow the same format, they just take in different tables.
