### ISSUE TITLE
Run a Maintain data migration on staging (cyder.nws.oregonstate.edu)

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/chili#18]
Tried to run it, asked me to set a list of reverse domains in settings, tried playing with it, and just said I'll leave it to murrown.

When you got time, send me your public key, and I'll get you access on the VM.

**Comment by ngokevin** [comment]
We're missing Ctnrs and Users right now on the staging

**Comment by murrown** [comment]
I migrated Ctnrs and Users. FFR, here are the commands to migrate:

dns_migrate -h for DNS objects
dhcp_migrate -h for DHCP objects
maintain_migrate -h for DNS objects and DNS builds, and DHCP objects will be included at some point in the future

**Comment by ngokevin** [comment]
sweet
