### ISSUE TITLE
Have the user/ctnr header box state "{user} {level} on {ctnr}"

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/chili#24]
e.g. 

```
ngoke
admin on
zone.wave
```

**Comment by church29** [comment]
{% if request.session.level == 0 %}
 <p> Guest on </p>
{% elif request.session.level == 1 %}
  <p> User on </p>
{% else %}
  <p> Admin on </p>
{% endif %}

Kind of long winded for what should be a lot simpler, but I don't know how to place ctnruser in the session.

**Comment by church29** [comment]
Temp solution is commited
