### ISSUE TITLE
Editing from DNS Detail pages should somehow pull the correct update form and slide it down

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/chili#26]
Perhaps have it POST to the generic cy_view which will handle the updates.

**Comment by church29** [comment]
Seems to be working to me. What exactly needs to be fixed? Do you want it to hide the list when updating?

**Comment by ngokevin** [comment]
this is from the detail page, @fridgei is doing something similar

**Comment by fridgei** [comment]
It is working now
