### ISSUE TITLE
Migrate Maintain "zones" to Ctnrs

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/chili#8]
V1
Migrate zones to Ctnrs with names and contacts

V2
Attach domains to Ctnrs

**Comment by murrown** [comment]
Zones are migrating, but I'm not sure how to handle contact information. In maintain, sometimes two e-mails are listed.

Domains can now be attached to Ctnrs with the -z flag, however, this blows up if the domain migrations are out of date, so cyder.nws has only a partial zone_domain migration.

**Comment by ngokevin** [comment]
hmm, i don't think i'd be opposed to concatenating the emails since they are just displayed in tables. @uberj ?
